USE MASTER 
GO

IF EXISTS (SELECT * FROM SYSDATABASES WHERE NAME ='HotelReservationSystem')
DROP DATABASE HotelReservationSystem
GO

CREATE DATABASE HotelReservationSystem
GO

USE HotelReservationSystem
GO

CREATE TABLE Customer
(
	CustomerID INT IDENTITY (1,1) PRIMARY KEY, 
	FirstName VARCHAR (30) NOT NULL, 
	LastName VARCHAR (30) NOT NULL, 
	PhoneNumber CHAR (10) NOT NULL, 
	Email VARCHAR (50) NOT NULL, 
	Age int NOT NULL, 
	Birthday DATETIME2 NOT NULL,
)

CREATE TABLE Promotion
(
	PromotionID INT IDENTITY (1,1) PRIMARY KEY, 
	PromotionName VARCHAR (50) NOT NULL, 
	StartDate DATETIME2 NULL, 
	EndDate DATETIME2 NULL, 
	PercentDiscount DECIMAL (5,2) NULL, 
	DollarAmountDiscount DECIMAL (5,2) NULL,
)

CREATE TABLE Reservation
(
	ReservationID INT IDENTITY (1,1) PRIMARY KEY,
	CustomerID INT FOREIGN KEY REFERENCES Customer(CustomerID) NOT NULL, 
	PromotionID	INT FOREIGN KEY REFERENCES Promotion(PromotionID) NULL,
	StartDate DATETIME2 NOT NULL, 
	EndDate DATETIME2 NOT NULL, 
)

CREATE TABLE AdditionalGuests
(
	ReservationID INT FOREIGN KEY REFERENCES Reservation(ReservationID) NOT NULL,
	FirstName VARCHAR (30) NOT NULL,
	LastName VARCHAR (30) NOT NULL,
	Age CHAR (3) NOT NULL,
)

CREATE TABLE Bill 
(
	BillID INT IDENTITY (1,1) PRIMARY KEY, 
	ReservationID INT FOREIGN KEY REFERENCES Reservation(ReservationID) NOT NULL,
	Total DECIMAL (20,2) NOT NULL, 
	Tax DECIMAL (20,2) NOT NULL,
)

CREATE TABLE AddOn
(
	AddOnID INT IDENTITY (1,1) PRIMARY KEY, 
	AddOnName VARCHAR (50) NOT NULL, 
)

CREATE TABLE BillAddOn
(
	BillID INT FOREIGN KEY REFERENCES Bill(BillID) NOT NULL, 
	AddOnID INT FOREIGN KEY REFERENCES AddOn(AddOnID) NOT NULL, 
	AddOnPrice DECIMAL (20,2) NOT NULL, 
	StartDate DATETIME2 NOT NULL, 
	EndDate DATETIME2 NOT NULL, 
	Quantity VARCHAR (10) NULL, 
)

CREATE TABLE Amenity
(
	AmenityID INT IDENTITY (1,1) PRIMARY KEY, 
	AmenityName VARCHAR (50) NOT NULL, 
)

CREATE TABLE Rate
( 
	RateID INT IDENTITY (1,1) PRIMARY KEY,
	RateName VARCHAR (50) NOT NULL,  
	RatePrice DECIMAL (20,2) NOT NULL,
	StartDate DATETIME2 NULL, 
	EndDate DATETIME2 NULL,
)

CREATE TABLE RoomType
(
	RoomTypeID INT IDENTITY (1,1) PRIMARY KEY, 
	TypeName VARCHAR (50) NOT NULL,
	RateID INT FOREIGN KEY REFERENCES Rate(RateID) NOT NULL,
)

CREATE TABLE Room
(
	RoomID INT IDENTITY (1,1) PRIMARY KEY, 
	RoomTypeID INT FOREIGN KEY REFERENCES RoomType(RoomTypeID) NOT NULL,
	RoomNumber VARCHAR(10) NOT NULL, 
	FloorLevel VARCHAR (10) NOT NULL, 
	OccupancyLimit VARCHAR (10) NOT NULL,
)

CREATE TABLE RoomAmenity
(
	RoomID INT FOREIGN KEY REFERENCES Room(RoomID) NOT NULL, 
	AmenityID INT FOREIGN KEY REFERENCES Amenity(AmenityID) NOT NULL, 
)

CREATE TABLE RoomReservation
(
	ReservationID INT FOREIGN KEY REFERENCES Reservation(ReservationID) NOT NULL, 
	RoomID INT FOREIGN KEY REFERENCES Room(RoomID) NOT NULL,
)

